### ISSUE TITLE
Class 'CommerceEasyPost\ShippingMethod' not found

### ISSUE THREAD

**Issue by lxcodes** [pixelandtonic/CommerceEasyPost#2] opened 2017-11-02 19:48 UTC
Currently getting the following error after installing and configuring while checking for the shipping methods correctness in Craft Commerce:

> #### Internal Server Error
> Class 'CommerceEasyPost\ShippingMethod' not found

As far as I can tell the plugin has the file with that namespace in a folder named the same.  Am I missing a step?

**Comment by lukeholder** [comment] 2017-11-04 05:49
What screen does the error apear on @al3x-edge ?

**Comment by lxcodes** [comment] 2017-11-06 14:47
@lukeholder This appears on the shipping methods screen in the Craft commerce settings section.

**Comment by mdunbavan** [comment] 2017-11-10 16:12
Hey @lukeholder sorry to be a pain but I see the same thing on the same page.

**Comment by lukeholder** [comment] 2017-11-11 04:43
Trying to reproduce. Can you send your dB dumps to support@craftcommerce.com thanks.

**Comment by ryanjavens** [comment] 2017-12-20 15:57
@lukeholder not sure if you've had any luck yet, but I believe this could be an issue with autoloader. If I add `require __DIR__.'/../CommerceEasyPost/ShippingMethod.php';` to the EasyPost_ShippingMethodsService.php file it fixes the issue. I noticed the last commit in this repo included an update to autoloader, so something could have broken there?

**Comment by ryanjavens** [comment] 2017-12-21 20:39
Looks like I've found a better solution. Adjusting https://github.com/pixelandtonic/CommerceEasyPost/blob/2883302e12fe4992bc55b16d7f04ecbce31933f1/easypost/composer.json#L14 and changing it to  `"CommerceEasyPost\\": "CommerceEasyPost"` and recreating the autoloader files seems to solve the issue without the messy pathing within the service file. In the latest commit, it looks like the compose file was moved into the easypost directory, which is what caused this path to break. I could make a pull request with this if you'd like @lukeholder !

**Comment by ryanjavens** [comment] 2018-01-23 18:40
@lukeholder @brandonkelly is there anything holding this up?

**Comment by lukeholder** [comment] 2018-01-24 01:19
@ryanjavens will confirm and get back you soon.

**Comment by lukeholder** [comment] 2018-02-01 08:23
Should be fixed in version 0.4 just released

**Closed as completed** 2018-02-01 08:23 UTC

**Comment by ryanjavens** [comment] 2018-02-01 13:26
Thank you!
